### ISSUE TITLE
[request]: More precise service account name matching in suggested AWS assume role policy

### ISSUE THREAD

**Issue by JonMerlevede** [datamindedbe/conveyor-roadmap#32]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want the service account names used for running jobs to be better documented, so that we can create an AWS assume role policy that matches only specific the service account names bound to specific projects.

The proposed policy as documented (https://docs.datafy.cloud/technical-reference/airflow/operators-aws-role) is currently:
```
data "aws_iam_policy_document" "default" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    condition {
      test     = "StringLike"
      variable = "${replace(var.aws_iam_openid_connect_provider_url, "https://", "")}:sub"
      values   = ["system:serviceaccount:${var.env_name}:${replace(local.project_name, "_", ".")}-*"]
    }

    principals {
      identifiers = [var.aws_iam_openid_connect_provider_arn]
      type        = "Federated"
    }
  }
}
```
The problem with this policy is that projects with name A that include the name of project B as a prefix, can assume a role meant for project B, e.g. project `jon-athan` can assume the role that's meant to only match project `jon`.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We use the assume role policy to ensure that every project can only read and manipulate data that is is authorized to.

**Are you currently working around this issue?**
We currently accept the risk.

**Additional context**
We use PBAC / "manually" pre-create roles specific to every combination of environment and project.

Possible solutions:
* make sure the random suffix is of fixed length, replace `*` by this number of `?` signs.
* use a separator that is not valid to use in the project name

**Comment by JonMerlevede** [comment]
Yep, sorry for not reading more carefully. I'd suggest dropping the second part of the more technical documentation and changing the default ~

```
locals {
  project_name = "sample"
  uuid_pattern = "????????-????-????-????-????????????"
}

resource "aws_iam_role" "default" {
  name               = "${local.project_name}-${var.env_name}"
  assume_role_policy = data.aws_iam_policy_document.default.json
}

data "aws_iam_policy_document" "default" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    condition {
      test     = "StringLike"
      variable = "${replace(var.aws_iam_openid_connect_provider_url, "https://", "")}:sub"
      values   = ["system:serviceaccount:${var.env_name}:${replace(local.project_name, "_", ".")}-${local.uuid_pattern}"]
    }

    principals {
      identifiers = [var.aws_iam_openid_connect_provider_arn]
      type        = "Federated"
    }
  }
}
```

**Comment by stijndehaes** [comment]
We have changed to docs on our main branched, it will be part of a next release. The templates also got updated: https://github.com/datamindedbe/conveyor-templates/pull/73
