### ISSUE TITLE
[request]: Support more or all docker build flags

### ISSUE THREAD

**Issue by din14970** [datamindedbe/conveyor-roadmap#34]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
datafy commands should ideally support all flags of `docker build`.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently `datafy build` and `datafy run` don't support all `docker build` flags. For some flags like `--no-cache` and `--progress=plain` this can be annoying.

**Are you currently working around this issue?**
Adding dummy edits to the dockerfile to force restarting the build from earlier stages to work around `--no-cache` and just using `docker build` with the right flags.

**Additional context**

**Attachments**

**Comment by pascal-knapen** [comment]
Tnx for the feedback Niels. This month we will be exploring support for podman next to docker (because of licencing issues). This might be a good time to also explore this issue.
