### ISSUE TITLE
[request]: Spark-Scala notebooks

### ISSUE THREAD

**Issue by genzov** [datamindedbe/conveyor-roadmap#35]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to use Spark-Scala notebooks, instead of just Python. The project I'm working on doesn't use PySpark and setting it up just for a notebook is more hassle than it's worth in the end.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It would be useful for experimenting and trying out code on the fly.

**Are you currently working around this issue?**
Building and deploying my code every time I want to change or try something.

**Comment by pascal-knapen** [comment]
Won't fix as scala is less and less used. We are also moving from Notebooks more and more to IDEs.
