### ISSUE TITLE
[request]: Clickable breadcrumbs

### ISSUE THREAD

**Issue by vlieven** [datamindedbe/conveyor-roadmap#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Not all levels of the UI breadcrumbs are currently clickable.

For instance, you have the breadcrumb "Projects/<{project name}>/Streaming Applications/<application name>"
Streaming Applications is currently not clickable, but could be made so.

**Comment by pascal-knapen** [comment]
Thanks @vlieven. I understand how this can make things easier 👍

**Comment by pascal-knapen** [comment]
Done
