### ISSUE TITLE
[request]: support "one-off" runable tasks separate from pipeline dags

### ISSUE THREAD

**Issue by din14970** [datamindedbe/conveyor-roadmap#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
By experimenting with the testing and other things, I've come to realize that it would be very convenient if there was an officially supported framework for defining tasks that do not get deployed as DAGs. Examples include running some tests in the correct environment, and cleaning up all artifacts from S3/Glue in the dev environment. These would be best triggered manually via datafy run. Maybe there could be a separate folder "run" or "tasks" that datafy run could access but that never get deployed.

**Are you currently working around this issue?**
We create DAGS for this and turn them off in the UI. It polutes the UI and feels kind of hacky.

**Additional context**

**Attachments**

**Comment by pascal-knapen** [comment]
You can use the AWS SDK for this: https://docs.conveyordata.com/how-to-guides/developer-tooling/python-sdk
