### ISSUE TITLE
[request]: GPU support in notebooks

### ISSUE THREAD

**Issue by vlieven** [datamindedbe/conveyor-roadmap#43]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
A way to use GPUs inside the Datafy notebooks.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to accelerate neural network training using a GPU. We're running in eu-west-3 (Paris), where the Sagemaker Notebook instances don't include GPU-supported ones. It would be a nice differentiator if this were possible through the Datafy notebooks instead.

**Are you currently working around this issue?**
No neural nets are being trained right now.

**Additional context**
This is not a super-urgent issue, but it would be nice to know if this is something which would be feasible in the future or not.

Thanks!

**Comment by pascal-knapen** [comment]
@vlieven Thanks for raising the issue. This is something that we will cover at some moment in time. Not concrete on the roadmap however.

**Comment by pascal-knapen** [comment]
Looking into better supporting GPUs beyond notebooks #72
