### ISSUE TITLE
[request]: Rollback functionality

### ISSUE THREAD

**Issue by vlieven** [datamindedbe/conveyor-roadmap#50]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Functionality that allows rolling back the deployed version in a certain environment to the previous version.
This could be a CLI command such as `datafy project rollback --env my_env`

**Are you currently working around this issue?**
Checking out the git commit that I want to roll back to, create a new build from that commit and deploy that build to the chosen environment.

**Comment by pascal-knapen** [comment]
@vlieven we will look into it.

**Comment by vlieven** [comment]
Functionality released in [1.10.5](https://docs.conveyordata.com/release-notes#1105-04-04-2023)
