### ISSUE TITLE
[request]: Ability to pin/favourite Projects and Environments

### ISSUE THREAD

**Issue by vlieven** [datamindedbe/conveyor-roadmap#51]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want to be able to flag certain projects and environments as important to me, in order to have them appear always on top in the UI list.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It would be nice to be able to pin/favourite Environments and Projects, with the intent of having these appear on the top of the list. Usually while developing on a certain project, you want to access it quickly, having it on top helps with this.

Likewise, you usually have a number of 'persisted' environments (dev/tst/acc/prd), along with a number of personal environments. Being able to pin the environments that you work on regularly allows you to quickly navigate to the things useful for you, and ignoring environments you never interact with.

This is not hard now, but to navigate to the "production" environment, I either have to type "pro" or navigate to the second page, or sort descending. This does not take a long time, but it is something I need to do each time, and I need to check production a lot.

**Are you currently working around this issue?**
Using the table navigation as it currently exists.

**Additional context**
You could also automate this by tracking user activity and sorting by frequently-accessed by default. I don't know which of these two solutions is easiest to implement or make the most sense, but either would solve my issue.

**Comment by pascal-knapen** [comment]
Thanks @vlieven. This is on our radar, no clear release date yet however.
