### ISSUE TITLE
[request]: Spark class name in airflow UI

### ISSUE THREAD

**Issue by mbiermans** [datamindedbe/conveyor-roadmap#63]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We would like to be able to see the spark class name that's being executed in Conveyor. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a couple of jobs that have the same name, but are in different packages. We could always look into the DAG code, but in general it would be easier if we could see this in the airflow UI which *exact* class is being executed.

**Are you currently working around this issue?**
Checking the class name in our DAG code instead of in the UI.

**Additional context**
Not really, it would just be a QoL improvement. 🙂 

**Attachments**
/

**Comment by pascal-knapen** [comment]
@mbiermans Thanks for the feedback! We will look into it!

**Comment by vlieven** [comment]
We've made the `java_class` parameter a templated field, which means you should be able to view it in the "Rendered Template" page of your task details. This should show you which class was used when running the operator. Hope this helps!
