### ISSUE TITLE
[request]: XCom support for ConveyorContainerOperatorV2

### ISSUE THREAD

**Issue by koosie0507** [datamindedbe/conveyor-roadmap#64]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to pass data between the `ConveyorContainerOperatorV2` tasks running in the same Airflow DAG via XCom.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

At the beginning of a DAG run I need to query a system for its current configuration values. Subsequent tasks in the DAG will overwrite those settings. At the end of the DAG run, the initial settings should be restored.

Airflow + XComArgs solve this problem. Working around this requires significant investment.

**Are you currently working around this issue?**

The current tentative workaround is using external storage(S3, etcd, Redis). When the amount of data exchanged between tasks is small, setting up new systems doesn't seem worth the effort. The added complexity of managing the correlation between tasks outside of Airflow is another drawback.

**Additional context**
-

**Attachments**
-

**Comment by stijndehaes** [comment]
@koosie0507 Thank you for your request! 

This request makes sense, we will look into this in the future

**Comment by nclaeys** [comment]
@koosie0507 This feature was released yesterday in Conveyor 1.10.4. More details about how it works can be found [in the docs](https://docs.conveyordata.com/how-to-guides/working-with-airflow/conveyor-use-xcoms)
