### ISSUE TITLE
[request]: Allow for easier reusage of shared code across multiple DAGs

### ISSUE THREAD

**Issue by qdegraaf** [datamindedbe/conveyor-roadmap#65]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We would like the ability to allow easier reusage of code throughout multiple dags without one of the solutions offered here:

https://docs.conveyordata.com/how-to-guides/working-with-airflow/conveyor-build-shared-code
https://docs.conveyordata.com/how-to-guides/working-with-airflow/common-project-with-airflow-utilities/

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We currently use the latter method, but as stated in the docs, it tightly couples airflow projects which is unwieldy. The alternative methods of simply skipping dag validation by default or building with a caught import error are also not preferable for reasons also mentioned in the instructions. (Having no validation and also catching ImportErrors in prod).

None of the above options are satisfying, and although it is of course good practice to have every DAG be self sufficient, there are a few utils here and there which definitely add value shared across DAGs. Considering we have loads of DAGs, the other other solution to just duplicate them everywhere is also unsatisfying.

**Are you currently working around this issue?**
We currently have `--skip-dag-validation` on by default for a lot of projects combined with the common-project-with-airflow-utiltities approach

**Additional context**
//

**Attachments**
//

**Comment by nclaeys** [comment]
@qdegraaf This feature was released yesterday in Conveyor 1.10.4. More details about how it works can be found [in the docs](https://docs.conveyordata.com/how-to-guides/working-with-airflow/conveyor-build-shared-code)

**Comment by qdegraaf** [comment]
Awesome thanks a lot! We'll look into implementing it right away!
