### ISSUE TITLE
[request]: Type hinting for conveyor operators

### ISSUE THREAD

**Issue by mbiermans** [datamindedbe/conveyor-roadmap#66]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Add a type hinting library / dependency we can install in our local development environment.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Since we started shifting to more general python development, we have integrated tools like mypy to do code analyses and type checking. We understand conveyor is closed-source, so you cannot just export these operators, but we would like to resolve these highlighting issues by some form of type hinting library.

**Are you currently working around this issue?**
How are you currently solving this problem?

We're looking into mocking the types (if that's even possible).

**Additional context**
Anything else we should know?

None.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
![image](https://user-images.githubusercontent.com/93517633/228523324-ef429e85-68c5-4502-a5b3-7ad2df29b2b3.png)

**Comment by vlieven** [comment]
Hi @mbiermans! We've just shipped the [types-conveyor](https://pypi.org/project/types-conveyor/) python package.
Feel free to give this a try and let us know if it fixes your issue :)
