### ISSUE TITLE
[DevExp]: IDE Support on Conveyor

### ISSUE THREAD

**Issue by stijndehaes** [datamindedbe/conveyor-roadmap#68]
The goal is to have IDE support on Conveyor. For a first release we will target a version of visual studio code running in the browser. User should be able to:
- Use the Conveyor CLI
- Use docker as this is a dependency of many command of the Conveyor CLI. This should be possible in a secure way
- Be able to checkout their git repositories
- Specify custom scripts that add certain dependencies to the IDE

**Comment by pascal-knapen** [comment]
Delivered with documentation here: https://docs.conveyordata.com/how-to-guides/conveyor-ides
